name: nix

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '**/*.nix'
      - 'flake.lock'
      - 'nix/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - '**/*.nix'
      - 'flake.lock'
      - 'nix/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: set up nix
        uses: cachix/install-nix-action@v31

      - name: check formatting
        run: |
          nix fmt
          if [ -n "$(git status --porcelain)" ]; then
            git --no-pager diff
            exit 1
          fi

      - name: check flake evaluation
        run: nix flake check
